name: 打包dep-vue3-ts项目
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 安装pnpm全局依赖
      run:
        npm install -g pnpm

    - name: 安装项目依赖和项目打包
      run:
        pnpm install && pnpm run build

    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: pnpm run preview